# Generated by Django 3.1.1 on 2020-09-23 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trafficsignal',
            old_name='long',
            new_name='lng',
        ),
    ]
