# Generated by Django 3.1.1 on 2020-10-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficlight',
            name='operationMode',
            field=models.CharField(choices=[('NL', 'Normal'), ('OR', 'OverRide')], default='NL', max_length=2),
        ),
        migrations.AddField(
            model_name='trafficlight',
            name='signalState',
            field=models.CharField(choices=[('RD', 'Red'), ('GR', 'Green')], default='RD', max_length=2),
        ),
        migrations.AddField(
            model_name='trafficsignal',
            name='controlIndex',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trafficsignal',
            name='controlList',
            field=models.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='trafficsignal',
            name='operationMode',
            field=models.CharField(choices=[('NL', 'Normal'), ('OR', 'OverRide')], default='NL', max_length=2),
        ),
        migrations.AddField(
            model_name='trafficsignal',
            name='timer',
            field=models.TimeField(auto_now=True),
        ),
    ]
