# Generated by Django 3.1.1 on 2020-10-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_auto_20201008_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficsignal',
            name='controlList',
            field=models.JSONField(default=list),
        ),
    ]
