# Generated by Django 3.1.1 on 2020-10-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_auto_20201008_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficsignal',
            name='controlList',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='trafficsignal',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='trafficsignal',
            name='lng',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
    ]
