# Generated by Django 3.1.1 on 2020-10-12 05:51

from django.db import migrations, models
import maps.models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_auto_20201012_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficsignal',
            name='controlList',
            field=models.JSONField(default=maps.models.controlListDefault),
        ),
    ]
