# Generated by Django 3.1.1 on 2020-10-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_auto_20201012_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficsignal',
            name='topicCreated',
            field=models.BooleanField(default=False),
        ),
    ]
