# Generated by Django 3.1.1 on 2020-10-12 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0008_trafficsignal_topiccreated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficsignal',
            name='topicCreated',
        ),
    ]
