# Generated by Django 3.1.1 on 2020-10-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0009_remove_trafficsignal_topiccreated'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_info', models.JSONField()),
            ],
        ),
    ]
