# Generated by Django 3.1.1 on 2020-10-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0010_hospitalroute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficsignal',
            name='controlIndex',
        ),
        migrations.RemoveField(
            model_name='trafficsignal',
            name='operationMode',
        ),
        migrations.AlterField(
            model_name='trafficsignal',
            name='timer',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
