# Generated by Django 3.1.1 on 2020-10-19 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0011_auto_20201019_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficsignal',
            name='timer',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 19, 21, 39, 12, 862273)),
        ),
    ]
