# Generated by Django 3.1.1 on 2020-12-05 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0015_auto_20201022_1548'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HospitalRoute',
            new_name='Route',
        ),
        migrations.AlterField(
            model_name='trafficlight',
            name='heartbeat',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 5, 21, 3, 52, 291774)),
        ),
        migrations.AlterField(
            model_name='trafficsignal',
            name='timer',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 5, 21, 3, 52, 160039)),
        ),
    ]
